### ISSUE TITLE
Unknown function 'gds.graph.exists'

### ISSUE THREAD

**Issue by soufianetahiri** [CravateRouge/autobloody#1]
Tested on a Kali

![image](https://user-images.githubusercontent.com/17729335/197973704-666f363c-df75-4467-88a3-a7d02c5158cd.png)

**Comment by soufianetahiri** [comment]
I guess I need Neo4j with the [GDS library](https://neo4j.com/docs/graph-data-science/current/installation/) :)

**Comment by CravateRouge** [comment]
Yes, for the list of dependencies see:
https://github.com/CravateRouge/autobloody#dependencies
